openapi: 3.0.0
info:
  version: 1.0.0
  title: ScriptNumerate 197311 sig
  description: Sigs for ACYCLOVIR 400 MG TABLET (197311)
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /99999/197311sig/v0.0.1/
    description: Get 197311 Sigs
tags:
  - name: KO Endpoints
    description: 197311 Endpoints
paths:
  /rxsigs:
    post:
      description: Compare Rx.
      operationId: comparerx
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    input:
      required:
        - rxcui
      properties:
        rxcui:
          type: string
          example: '197311'
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: '{"rxcui":"197311":sigs:[]}'
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
