openapi: 3.0.0
info:
  version: 1.0.0
  title: ScriptNumerate 197319
  description: Prescribing Pattern for ALLOPURINOL 100 MG TABLET (197319)
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /99999/197319/v0.0.1/
    description: Compare 197319 Rx
tags:
  - name: KO Endpoints
    description: 197319 Endpoints
paths:
  /rxcompare:
    post:
      description: Compare Rx.
      operationId: comparerx
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    input:
      required:
        - rxdata
      properties:
        rxdata:
          type: string
          example: 50 MG ONCE
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: >-
            RESULT:RARE --SUMMARY: 50 MG ONCE is rare within 365 presriptions on
            file ---FREQUENCY = 0.00
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
